version: '3.8'

services:
  detection-api:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: detection-api:latest
    container_name: detection-api
    ports:
      - "5000:5000"

  streamlit-web:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    image: detection-service:latest
    container_name: detection-service
    ports:
      - "8501:8501"
